/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface DCIPGovernorInterface extends ethers.utils.Interface {
  functions: {
    "blockAddress(address)": FunctionFragment;
    "blockedAddresses(address)": FunctionFragment;
    "castVote(uint256,bool)": FunctionFragment;
    "getProposal(uint256)": FunctionFragment;
    "getVote(address,uint256)": FunctionFragment;
    "getVotingWeight(address)": FunctionFragment;
    "hasVoted(address,uint256)": FunctionFragment;
    "invalidateProposal(uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "proposalCount()": FunctionFragment;
    "proposalReward()": FunctionFragment;
    "proposalThreshold()": FunctionFragment;
    "propose(string,string,uint256)": FunctionFragment;
    "quorumReached(uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setProposalReward(uint16)": FunctionFragment;
    "setProposalTreshhold(uint256)": FunctionFragment;
    "setVotesForQuorum(uint256)": FunctionFragment;
    "setVotingPeriod(uint64)": FunctionFragment;
    "token()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "unblockAddress(address)": FunctionFragment;
    "voteSucceeded(uint256)": FunctionFragment;
    "votesForQuorum()": FunctionFragment;
    "votingPeriodBlocks()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "blockAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "blockedAddresses",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "castVote",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVote",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVotingWeight",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "invalidateProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proposalCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposalReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposalThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "propose",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "quorumReached",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setProposalReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setProposalTreshhold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setVotesForQuorum",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setVotingPeriod",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "unblockAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "voteSucceeded",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "votesForQuorum",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "votingPeriodBlocks",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "blockAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blockedAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "castVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVotingWeight",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "invalidateProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposalReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposalThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "propose", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "quorumReached",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProposalReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProposalTreshhold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVotesForQuorum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVotingPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unblockAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteSucceeded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "votesForQuorum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "votingPeriodBlocks",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "ProposalCreated(uint256,string,uint256)": EventFragment;
    "VoteCast(address,uint256,bool,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProposalCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VoteCast"): EventFragment;
}

export class DCIPGovernor extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: DCIPGovernorInterface;

  functions: {
    blockAddress(
      adr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    blockedAddresses(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    castVote(
      proposalId: BigNumberish,
      support: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getProposal(
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        string,
        string,
        BigNumber,
        [BigNumber] & { _deadline: BigNumber },
        [BigNumber] & { _deadline: BigNumber },
        boolean,
        BigNumber,
        BigNumber,
        BigNumber,
        number
      ] & {
        id: BigNumber;
        proposer: string;
        title: string;
        description: string;
        fundAllocation: BigNumber;
        voteStart: [BigNumber] & { _deadline: BigNumber };
        voteEnd: [BigNumber] & { _deadline: BigNumber };
        executed: boolean;
        votesAgainst: BigNumber;
        votesFor: BigNumber;
        votesForQuorum: BigNumber;
        proposalState: number;
      }
    >;

    getVote(
      account: string,
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getVotingWeight(
      voter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    hasVoted(
      account: string,
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    invalidateProposal(
      proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    proposalCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    proposalReward(overrides?: CallOverrides): Promise<[number]>;

    proposalThreshold(overrides?: CallOverrides): Promise<[BigNumber]>;

    propose(
      title: string,
      description: string,
      fundAllocation: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    quorumReached(
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setProposalReward(
      _proposalReward: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setProposalTreshhold(
      _threshold: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setVotesForQuorum(
      nrOfTokens: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setVotingPeriod(
      period: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    token(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unblockAddress(
      adr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    voteSucceeded(
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    votesForQuorum(overrides?: CallOverrides): Promise<[BigNumber]>;

    votingPeriodBlocks(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  blockAddress(
    adr: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  blockedAddresses(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  castVote(
    proposalId: BigNumberish,
    support: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getProposal(
    proposalId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      string,
      string,
      string,
      BigNumber,
      [BigNumber] & { _deadline: BigNumber },
      [BigNumber] & { _deadline: BigNumber },
      boolean,
      BigNumber,
      BigNumber,
      BigNumber,
      number
    ] & {
      id: BigNumber;
      proposer: string;
      title: string;
      description: string;
      fundAllocation: BigNumber;
      voteStart: [BigNumber] & { _deadline: BigNumber };
      voteEnd: [BigNumber] & { _deadline: BigNumber };
      executed: boolean;
      votesAgainst: BigNumber;
      votesFor: BigNumber;
      votesForQuorum: BigNumber;
      proposalState: number;
    }
  >;

  getVote(
    account: string,
    proposalId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getVotingWeight(
    voter: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  hasVoted(
    account: string,
    proposalId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  invalidateProposal(
    proposalId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  proposalCount(overrides?: CallOverrides): Promise<BigNumber>;

  proposalReward(overrides?: CallOverrides): Promise<number>;

  proposalThreshold(overrides?: CallOverrides): Promise<BigNumber>;

  propose(
    title: string,
    description: string,
    fundAllocation: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  quorumReached(
    proposalId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setProposalReward(
    _proposalReward: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setProposalTreshhold(
    _threshold: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setVotesForQuorum(
    nrOfTokens: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setVotingPeriod(
    period: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  token(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unblockAddress(
    adr: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  voteSucceeded(
    proposalId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  votesForQuorum(overrides?: CallOverrides): Promise<BigNumber>;

  votingPeriodBlocks(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    blockAddress(adr: string, overrides?: CallOverrides): Promise<boolean>;

    blockedAddresses(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    castVote(
      proposalId: BigNumberish,
      support: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProposal(
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        string,
        string,
        BigNumber,
        [BigNumber] & { _deadline: BigNumber },
        [BigNumber] & { _deadline: BigNumber },
        boolean,
        BigNumber,
        BigNumber,
        BigNumber,
        number
      ] & {
        id: BigNumber;
        proposer: string;
        title: string;
        description: string;
        fundAllocation: BigNumber;
        voteStart: [BigNumber] & { _deadline: BigNumber };
        voteEnd: [BigNumber] & { _deadline: BigNumber };
        executed: boolean;
        votesAgainst: BigNumber;
        votesFor: BigNumber;
        votesForQuorum: BigNumber;
        proposalState: number;
      }
    >;

    getVote(
      account: string,
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getVotingWeight(
      voter: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hasVoted(
      account: string,
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    invalidateProposal(
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    proposalCount(overrides?: CallOverrides): Promise<BigNumber>;

    proposalReward(overrides?: CallOverrides): Promise<number>;

    proposalThreshold(overrides?: CallOverrides): Promise<BigNumber>;

    propose(
      title: string,
      description: string,
      fundAllocation: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    quorumReached(
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setProposalReward(
      _proposalReward: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    setProposalTreshhold(
      _threshold: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    setVotesForQuorum(
      nrOfTokens: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setVotingPeriod(
      period: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    token(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    unblockAddress(adr: string, overrides?: CallOverrides): Promise<boolean>;

    voteSucceeded(
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    votesForQuorum(overrides?: CallOverrides): Promise<BigNumber>;

    votingPeriodBlocks(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    ProposalCreated(
      id?: null,
      title?: null,
      fundAllocation?: null
    ): TypedEventFilter<
      [BigNumber, string, BigNumber],
      { id: BigNumber; title: string; fundAllocation: BigNumber }
    >;

    VoteCast(
      account?: null,
      proposalId?: null,
      support?: null,
      weight?: null
    ): TypedEventFilter<
      [string, BigNumber, boolean, BigNumber],
      {
        account: string;
        proposalId: BigNumber;
        support: boolean;
        weight: BigNumber;
      }
    >;
  };

  estimateGas: {
    blockAddress(
      adr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    blockedAddresses(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    castVote(
      proposalId: BigNumberish,
      support: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getProposal(
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVote(
      account: string,
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVotingWeight(
      voter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    hasVoted(
      account: string,
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    invalidateProposal(
      proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    proposalCount(overrides?: CallOverrides): Promise<BigNumber>;

    proposalReward(overrides?: CallOverrides): Promise<BigNumber>;

    proposalThreshold(overrides?: CallOverrides): Promise<BigNumber>;

    propose(
      title: string,
      description: string,
      fundAllocation: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    quorumReached(
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setProposalReward(
      _proposalReward: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setProposalTreshhold(
      _threshold: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setVotesForQuorum(
      nrOfTokens: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setVotingPeriod(
      period: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    token(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unblockAddress(
      adr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    voteSucceeded(
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    votesForQuorum(overrides?: CallOverrides): Promise<BigNumber>;

    votingPeriodBlocks(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    blockAddress(
      adr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    blockedAddresses(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    castVote(
      proposalId: BigNumberish,
      support: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getProposal(
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVote(
      account: string,
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVotingWeight(
      voter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    hasVoted(
      account: string,
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    invalidateProposal(
      proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proposalCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proposalReward(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proposalThreshold(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    propose(
      title: string,
      description: string,
      fundAllocation: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    quorumReached(
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setProposalReward(
      _proposalReward: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setProposalTreshhold(
      _threshold: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setVotesForQuorum(
      nrOfTokens: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setVotingPeriod(
      period: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    token(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unblockAddress(
      adr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    voteSucceeded(
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    votesForQuorum(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    votingPeriodBlocks(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
